"""add updated columns

Revision ID: 50203e116dcf
Revises: 7cfaa7eaf6f7
Create Date: 2026-04-06 16:19:21.258836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50203e116dcf'
down_revision: Union[str, Sequence[str], None] = '7cfaa7eaf6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('difficulty', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('options', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'options')
    op.drop_column('questions', 'difficulty')
    # ### end Alembic commands ###
