"""add exam_type to examinations

Revision ID: 7ba5ed69e005
Revises: a362a311295d
Create Date: 2026-04-16 16:53:44.269171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ba5ed69e005'
down_revision: Union[str, Sequence[str], None] = 'a362a311295d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('examinations', sa.Column('exam_type', sa.String(), nullable=True))
    op.drop_index(op.f('ix_subjects_code'), table_name='subjects')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_subjects_code'), 'subjects', ['subject_code'], unique=False)
    op.drop_column('examinations', 'exam_type')
    # ### end Alembic commands ###
